flaskr/routes.py
from datetime import datetime
import threading, time, json, random
from flask import current_app as app
from flask import Blueprint, render_template, flash, request, redirect, copy_current_request_context
from flaskr.models import db, Settings, EnvironmentData, Stats
from flaskr.utils import umConversions
import plotly
import plotly.graph_objs as graphObject
import pandas as pd

sensorSimulation = False
try:
    from sense_hat import SenseHat
    sense = SenseHat()
except (RuntimeError, ModuleNotFoundError):
    from flaskr.utils.senseHatMock import SenseHatMock
    sense = SenseHatMock()
    sensorSimulation = True

from flask_socketio import SocketIO

socketio = SocketIO()

stop_event = threading.Event()
daemon = threading.Thread()
isDaemonStarted = False

environmentData = EnvironmentData()

view = Blueprint("view", __name__)

@view.context_processor
def inject_settings():
    settings = Settings.query.get(1)
    return dict(settings=settings)

@view.route("/")
def homepage():
    settings = Settings.query.get(1)
    return render_template("homepage.html", settings=settings)

@view.route("/settings")
def settings():
    settings = Settings.query.get(1)
    return render_template("settings.html", settings=settings)

@view.route("/deleteStats")
def deleteStats():
    try:
        db.session.query(Stats).delete()
        db.session.commit()
        msg = "All stats successfully deleted"
        flash(msg)
    except Exception as e:
        msg = "Failed to delete stats"
        print(e)
        flash(msg)
    return redirect("/stats")

@view.route("/stats")
def stats():
    stats = Stats.query.all()
    return render_template("stats.html", stats=stats)

@view.route("/update", methods=["POST"])
def update():
    try:
        requestDataToDB(request, db)
        db.session.commit()
        return redirect("/")
    except Exception as e:
        msg = "Failed to update settings"
        print(e)
        flash(msg)
    return redirect("/settings")

@socketio.on('connect')
def on_connect():
    socketio.emit('daemonProcess', getEnvironmentData().toJson())

@socketio.on('handleDaemon')
def on_handleDaemon(data):
    action=data['action']

    @copy_current_request_context
    def daemonProcess(name, stop_event):
        while not stop_event.is_set():
            emitIfChanges()
            time.sleep(int(Settings.query.get(1).readFromSensorInterval))
    
    def emitIfChanges():
        if(isDataChanged()):
            socketio.emit('daemonProcess', getEnvironmentData().toJson())

    global isDaemonStarted
    if action == 'START':
        if not isDaemonStarted:
            daemon.__init__(target=daemonProcess, args=('ThermoPi', stop_event), daemon=True)
            daemon.start()
            isDaemonStarted = True
    else:
        stop_event.set()
        daemon.join()
        stop_event.clear()
        isDaemonStarted = False

def requestDataToDB(request, db):
    temperatureUm = request.form.get("temperatureUm")
    readFromSensorInterval = request.form.get("readFromSensorInterval")

    minDeltaDataTrigger = request.form.get("minDeltaDataTrigger")
    temperatureCorrection = request.form.get("temperatureCorrection")
    humidityCorrection = request.form.get("humidityCorrection")
    pressureCorrection = request.form.get("pressureCorrection")
    storeStatsDataLimit = request.form.get("storeStatsDataLimit")
    
    showLastEvent = request.form.get("showLastEvent")
    settings = Settings.query.get(1)
    settings.temperatureUm = temperatureUm
    settings.readFromSensorInterval = readFromSensorInterval

    settings.minDeltaDataTrigger = float( '0.0' if minDeltaDataTrigger == '' else minDeltaDataTrigger )
    settings.temperatureCorrection = float( '0.0' if temperatureCorrection == '' else temperatureCorrection )
    settings.humidityCorrection = int( '0' if humidityCorrection == '' else humidityCorrection )
    settings.pressureCorrection = int( '0' if pressureCorrection == '' else pressureCorrection )
    settings.storeStatsDataLimit = int( '0' if storeStatsDataLimit == '' else storeStatsDataLimit )

    settings.showLastEvent = 0
    if showLastEvent == 'on':
        settings.showLastEvent = 1

def setEnvironmentDataValues():
    temperatureCorrection = float(Settings.query.get(1).temperatureCorrection)
    humidityCorrection = int(Settings.query.get(1).humidityCorrection)
    pressureCorrection = int(Settings.query.get(1).pressureCorrection)
    temperature = round(sense.get_temperature(), 1)
    humidity = round(sense.get_humidity(), 1)
    pressure = int(sense.get_pressure())
    temperatureUm = Settings.query.get(1).temperatureUm
    if (temperatureUm == '°F'):
        temperature = umConversions.celsiusToFahrenheit(temperature, 1)
    humidityUm = '%'
    pressureUm = 'mBar'

    temperature = round(temperature + temperatureCorrection, 1)
    humidity = round(humidity + humidityCorrection, 1)
    pressure = round(pressure + pressureCorrection, 1)
    dateTime = str(datetime.now())

    getEnvironmentData().set_dateTime(dateTime)
    getEnvironmentData().set_temperature(temperature) 
    getEnvironmentData().set_humidity(humidity)
    getEnvironmentData().set_pressure(pressure)
    getEnvironmentData().set_temperatureUm(temperatureUm)  
    getEnvironmentData().set_humidityUm(humidityUm)
    getEnvironmentData().set_pressureUm(pressureUm)
    getEnvironmentData().set_sensorSimulation(sensorSimulation)

    dataLimit = int(Settings.query.get(1).storeStatsDataLimit) 
    if (dataLimit > 0):
        numberOfRecords = db.session.query(Stats).count()
        if (numberOfRecords < dataLimit):
            storeStatsData(temperature, humidity, pressure, temperatureUm, humidityUm, pressureUm, sensorSimulation)

def getEnvironmentData():
    return environmentData

def isDataChanged():
    previousTemperature = getEnvironmentData().get_temperature()
    setEnvironmentDataValues()
    currentTemperature = getEnvironmentData().get_temperature()
    deltaAbs = abs(abs(previousTemperature) - abs(currentTemperature))
    minDeltaDataTrigger = float(Settings.query.get(1).minDeltaDataTrigger)
    return deltaAbs >= minDeltaDataTrigger

def storeStatsData(temperature, humidity, pressure, temperatureUm, humidityUm, pressureUm, sensorSimulation):
    stats = Stats()
    stats.temperature = temperature
    stats.humidity = humidity
    stats.pressure = pressure
    stats.temperatureUm = temperatureUm
    stats.humidityUm = humidityUm
    stats.pressureUm = pressureUm
    stats.sensorSimulation = sensorSimulation

    db.session.add(stats)
    db.session.commit()

flaskr/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.svg') }}">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
        
        <!-- DARK MODE -->
        <link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.css">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/thphat_pi.css') }}">

        <link rel="stylesheet" href="{{ url_for('static', filename='css/nouislider.css') }}">

        <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap4.min.css"/>

        <title>THPHat Pi</title>
    </head>

    <body onload="initOnLoad();">
        <script src="{{ url_for('static', filename='js/init.js') }}"></script>
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>

        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script>

        <script src="{{ url_for('static', filename='js/socketIO.js') }}"></script>

        <script src="{{ url_for('static', filename='js/nouislider.js') }}"></script>

        <script src="{{ url_for('static', filename='js/plotly.js') }}"></script>

        <!-- ENABLE EXPORT BUTTONS DATATABLE -->
        <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.bootstrap4.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.colVis.min.js"></script>

        <!-- PLOTLY -->
        <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <a class="navbar-brand" href="{{ url_for('view.homepage') }}" data-toggle="tooltip" title="THPHat Pi">
                <div>
                    <div class="row">
                        <div class="col">
                            <img src="{{ url_for('static', filename='img/logo.svg') }}" class="logo">
                        </div>
                    </div>
                </div>
            </a>
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>            

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto"> 
                    <li class="nav-item active">
                        <a class="nav-item nav-link" href="{{ url_for('view.homepage') }}" title="Home">
                            Home
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-item nav-link" href="{{ url_for('view.stats') }}" title="Stats">
                            Stats
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-item nav-link" href="{{ url_for('view.settings') }}" title="Settings">
                            Settings
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-item nav-link" href="{{ url_for('view.settings') }}" data-toggle="modal"  data-target="#aboutModal" title="About">
                            About
                        </a>
                    </li>
                </ul>
            </div>

        </nav>

        <div>
            <div class="row">
                <div class="col">
                    <p id="digitalClock" class="digitalClock"></p>
                    <p id="sensorSimulation" class="sensorSimulation blink_me">Sensor not found, data simulation</p>
                    <p id="lastEvent" class="lastEvent" {% if settings.showLastEvent == 0 %} hidden {% endif %}></p>
                </div>
            </div>
        </div>

        {% block content %}
        {% endblock %}

        <div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="aboutModalLabel"> <img src="{{ url_for('static', filename='img/logo.svg') }}" class="logo about"> THPHat Pi </h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <p class="about-text"> Temperature/Humidity/Pressure sensor control with <a href="https://www.raspberrypi.org/" rel="noopener noreferrer" target="_blank"> 
                                    Raspberry Pi </a> and <a href="https://www.raspberrypi.org/products/sense-hat/" rel="noopener noreferrer" target="_blank"> 
                                    Sense Hat </a> board.
                                <br>
                                Code at <a href="https://github.com/francoparodi/THPHat_pi.git" rel="noopener noreferrer" target="_blank"> THPHat Pi</a>
                            </p>
                        </div>
                    </div>
                </div>
              </div>
            </div>
          </div>

    </body>

</html>

flaskr/templates/homepage.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="container content-container">

  <div class="row">

    <div class="col">
      <div class="row">
        <div class="col img-data-col">
          <img src="{{ url_for('static', filename='img/temperature.svg') }}" class="imgTemperature">
        </div>
        <div class="col">
          <p class="units-data-temperature">{{ settings.temperatureUm }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <p class="temperature" id="temperature"></p>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="row">
        <div class="col img-data-col">
          <img src="{{ url_for('static', filename='img/humidity.svg') }}" class="imgHumidity">
        </div>
        <div class="col">
          <p class="units-data-humidity">{{ settings.humidityUm }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <p class="humidity" id="humidity"></p>
        </div>
      </div>
    </div>

    <div class="col">
      <div class="row">
        <div class="col img-data-col">
          <img src="{{ url_for('static', filename='img/pressure.svg') }}" class="imgPressure">
        </div>
        <div class="col">
          <p class="units-data-pressure">{{ settings.pressureUm }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <p class="pressure" id="pressure"></p>
        </div>
      </div>
    </div>

  </div>
          
</div>

<div class="container content-container">
  <div class="mt-3" id="graphId">

  </div>
</div>

{% endblock %}

flaskr/templates/settings.html
{% extends 'base.html' %}

{% block content %}

    <div class="container content-container">
        <div class="mt-3">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-dark" role="alert">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        </div>
    </div>

    <div class="container content-container">
        <form method="POST" action="/update">
            <div class="form-group">

                <div>
                    <label for="temperatureUm">Temperature Units</label>
                    <select type="text" class="form-control temperatureUm" id="temperatureUm" name="temperatureUm" >
                        <option value="°C" {% if settings.temperatureUm == '°C' %} selected {% endif %}>° Celsius</option>
                        <option value="°F" {% if settings.temperatureUm == '°F' %} selected {% endif %}>° Fahrenheit</option>
                    </select>
                </div> 
 
                <div>
                    <label id="sensorIntervalSliderLabel" for="readFromSensorIntervalSlider"></label>
                    <input id="readFromSensorIntervalSliderValue" type="hidden" name="readFromSensorInterval" value="{{ settings.readFromSensorInterval }}">                    
                    <div id="readFromSensorIntervalSlider"></div>
                    <script>
                        createSlider('readFromSensorIntervalSlider', 'readFromSensorIntervalSliderValue');
                    </script>
                </div>

                <div>
                    <label for="minDeltaDataTrigger">Temperature variation trigger</label>
                    <input class="form-control form-input-number" type="number" value="{{ settings.minDeltaDataTrigger }}" name="minDeltaDataTrigger" min="0.1" max="50" step="0.1" id="minDeltaDataTrigger">
                </div>

                <div>
                    <label for="temperatureCorrection">Temperature factor correction (+/-)</label>
                    <input class="form-control form-input-number" type="number" value="{{ settings.temperatureCorrection }}" name="temperatureCorrection" min="-50.0" max="50.0" step="0.5" id="temperatureCorrection">
                </div>

                <div>
                    <label for="humidityCorrection">Humidity factor correction (+/-)</label>
                    <input class="form-control form-input-number" type="number" value="{{ settings.humidityCorrection }}" name="humidityCorrection" min="-50" max="50" step="1" id="humidityCorrection">
                </div>

                <div>
                    <label for="pressureCorrection">Pressure factor correction (+/-)</label>
                    <input class="form-control form-input-number" type="number" value="{{ settings.pressureCorrection }}" name="pressureCorrection" min="-500" max="500" step="1" id="pressureCorrection">
                </div>

                <div>
                    <label for="storeStatsDataLimit">Stats data limit (0=no store)</label>
                    <input class="form-control form-input-number" type="number" value="{{ settings.storeStatsDataLimit }}" name="storeStatsDataLimit" min="0" max="99999" step="1" id="storeStatsDataLimit">
                </div>

                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" name="showLastEvent" id="showLastEvent" {% if settings.showLastEvent == 1 %} checked {% endif %}>
                    <label class="custom-control-label" for="showLastEvent">Show last event</label>
                </div>

            </div>

            <button type="submit" class="btn btn-primary">Update</button>
            <a class="btn btn-primary" href="{{ url_for('view.homepage') }}" role="button">Back</a>
        </form>
    </div>

{% endblock %}

flaskr/templates/stats.html
{% extends 'base.html' %}

{% block content %}

<script>
    $(document).ready(function() {
        $('#stats_table').DataTable( {
            dom: 'Bftipr',
            "pageLength": 8,
            buttons: [ 'csv', 'pdf', 'copy' ]
        });
    } );
</script>

<div class="container content-container">
    <div class="mt-3">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-dark" role="alert">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    </div>
</div>

<div class="container content-container">

        <table id="stats_table" class="table table-sm stats-table-smaller">
            <thead>
                <tr>
                    <th scope="col">Temperature</th>
                    <th scope="col">Humidity</th>
                    <th scope="col">Pressure</th>
                    <th scope="col">Event</th>
                </tr>
            </thead>
            <tbody>
            {% for stat in stats %}
                <tr>
                    <td>{{ stat.temperature }} {{ stat.temperatureUm }}</td>
                    <td>{{ stat.humidity }} {{ stat.humidityUm }}</td>
                    <td>{{ stat.pressure }} {{ stat.pressureUm }}</td>
                    <td>{{ stat.created_at }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div>
            <a class="btn btn-primary" href="{{ url_for('view.stats') }}" role="button">Refresh</a>
            <a class="btn btn-primary" href="{{ url_for('view.deleteStats') }}" role="button">Delete stats</a>
        </div>

</div>

{% endblock %}